### ISSUE TITLE
issue when using css

### ISSUE THREAD

**Issue by chrisdrackett** [just-boris/react-app-styleguidist#1]
I'm trying to add a global css file using the following:
https://github.com/just-boris/react-app-styleguidist/blob/master/styleguide.config.js#L14

but when I start the style guide I get:

```
Module parse failed: /src/index.css Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
```

**Comment by just-boris** [comment]
Did you close the issue?
Does that mean that you have found a solution?

**Comment by chrisdrackett** [comment]
yep, I missed something in my webpack config, sorry about that!
