### ISSUE TITLE
Deprecate package

### ISSUE THREAD

**Issue by sapegin** [just-boris/react-app-styleguidist#3]
React Styleguidist supports create-react-app out of the box since 5.0, so there’s no need for extra package anymore.

🐙

**Comment by just-boris** [comment]
That's true.
Updated the readme, also added a deprecation warning to `npm install`. 
Hope it will be enough!

Thank you for the effort bringing this into core!

**Comment by sapegin** [comment]
Awesome, thanks! I’ve also sent a new PR to CRA: https://github.com/facebookincubator/create-react-app/pull/2044
